### ISSUE TITLE
MS Edge: SCRIPT1005: SCRIPT1005: Expected '(' app.d1dcbf89.js (1,20301)

### ISSUE THREAD

**Issue by stuk-samu** [StukFi/opendata#32]
```
... }catch{localStorage.removeItem(l)}}} ...
```

Ilmeisesti tämä kohta: https://github.com/StukFi/opendata/blob/master/src/models/Settings.js#L53

**Comment by lmalmber** [comment]
En saa toistumaan Edgellä, kun pakotan tuon catch statementin. Voisiko johtua vanhemmasta Edge-versiosta? Omalla työkoneella on Version 87.0.664.75 (Official build) (64-bit).

Sinänsä sivuhuomiona nuo map legendin tallennukset local storageen voisi ottaa pois, sillä 2.0 versiossa käyttäjä ei voi vaihtaa map legendin raja-arvoja asetus-paneelista.

**Comment by stuk-samu** [comment]
Tämä on havaittu versiolla 44.17763.831.0, joka ei ole Chromium-pohjainen.
